williams_simon/musicapp/config/routes.rb
Rails.application.routes.draw do

  resources :artists do
    resources :songs
    post 'songs/:id' => 'songs#listen', :as => 'listen_song'
  end

  get 'songs/all' => 'songs#all'

  delete 'songs/destroy' => 'songs#destroy_song'
  
  resources :labels

  post 'labels/:id' => 'labels#show'

  root "artists#index"

end

williams_simon/musicapp/app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :songs, :dependent => :delete_all
	belongs_to :label
	validates :artist_name, uniqueness: true
end

williams_simon/musicapp/app/models/label.rb
class Label < ActiveRecord::Base
	has_many :artists
	validates :label_name, uniqueness: true
end

williams_simon/musicapp/app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
end

williams_simon/musicapp/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

	def index
		@artists = Artist.all
	end

	def new
		@artist = Artist.new
	end

	def create
		@artist = Artist.create(artist_params)
		@artist.label_id = params[:label][:label_id]
		@artist.update(artist_params)
		redirect_to artists_path
	end

	def edit
		@artist = Artist.find(params[:id])
	end

	def update
		@artist = Artist.find(params[:id])
		@artist.label_id = params[:label][:label_id]
		@artist.update(artist_params)
		redirect_to artists_path
	end

	def destroy
		@artist = Artist.find(params[:id])
		@artist.destroy
		redirect_to artists_path
	end

	def show
		@artist = Artist.find(params[:id])
	end


	private
		def artist_params
			params.require(:artist).permit(:artist_name, :artist_age, :label_id) 
		end

end

williams_simon/musicapp/app/controllers/labels_controller.rb
class LabelsController < ApplicationController

	def index
		@labels = Label.all
	end

	def new
		@label = Label.new
	end

	def create
		@label = Label.create(label_params)
		redirect_to labels_path
	end

	def edit
		@label = Label.find(params[:id])
	end

	def update
		@label = Label.find(params[:id])
		@label.update(label_params)
		redirect_to labels_path
	end

	def show
		@label = Label.find(params[:id])
	end

	def destroy
		@label = Label.find(params[:id])
		@label.destroy
		redirect_to labels_path
	end

	private

	def label_params
		params.require(:label).permit(:label_name)
	end


end

williams_simon/musicapp/app/controllers/songs_controller.rb
class SongsController < ApplicationController

	def all
		@songs = Song.all.order(:song_name)
	end

	def index
	   	@artist = Artist.find(params[:artist_id])
	end

	def new
		@artist = Artist.find(params[:artist_id])
	end

	def create
		@artist = Artist.find(params[:artist_id])
		@song = @artist.songs.create(song_params)
   		redirect_to artist_songs_path(@artist)
	end

	def edit
		@artist = Artist.find(params[:artist_id])
		@song = Song.find(params[:id])
	end

	def update
		@song = Song.find(params[:id])
		@song.update(song_params)
		redirect_to artist_songs_path
	end

	def destroy
		@song = Song.find(params[:id])
		@song.destroy
		redirect_to artist_songs_path
	end

	def destroy_song
		binding.pry
		@song = Song.find(params[:format])
		binding.pry
		@song.destroy
		redirect_to songs_all_path
	end

	def show
		@song = Song.find(params[:id])
	end

	def listen
		# Find the song
		@song = Song.find(params[:id])
		@artist_song_detail = RapGeniusApi.search_for_songs(@song.song_name, @song.artist.artist_name)
	end


	
	private
	    def song_params
  	    params.require(:song).permit(:song_name, :genre, :duration, :release_date)
  		end
end

williams_simon/musicapp/app/helpers/artist_helper.rb
module ArtistHelper
end

williams_simon/musicapp/app/helpers/labels_helper.rb
module LabelsHelper
end

williams_simon/musicapp/app/helpers/songs_helper.rb
module SongsHelper
end

williams_simon/musicapp/app/views/artists/_artist_details.html.erb
<table class="table table-responsive table-bordered table-hover">
  <tr>
    <th>Artist Name</th>
    <th>Age</th>
    <th>Label</th>
  </tr>
	<% @artists.each do |artist| %>
		<tr>
			<td> <%=link_to "#{artist.artist_name}", artist_path(artist) %> </td>
			<td><%= artist.artist_age %></td>
			<td> <%=link_to "#{artist.label.label_name}", labels_path %> </td>
			<td class="col-xs-1"><%= link_to "View artist songs", artist_songs_path(artist), 
					:class => 'btn btn-primary' %></td>
			<td class="col-xs-1"><%= link_to "Edit artist", edit_artist_path(artist),
					:class => 'btn btn-info' %></td>
			<td class="col-xs-1"><%= link_to "Delete artist", artist_path(artist),
					method: :delete, data: { confirm: 'Are you sure?' },
					:class => 'btn btn-danger' %></td>
		</tr>
	<% end %>
</table>
<%= link_to "Create a new artist", new_artist_path, :class => 'btn btn-success' %>
<%= link_to "View all songs", songs_all_path, :class => 'btn btn-success' %>
<%= link_to "View all labels", labels_path, :class => 'btn btn-success' %>

williams_simon/musicapp/app/views/artists/_form.html.erb
<div class="well">
<%= simple_form_for(@artist, html: {:class => 'form-horizontal'}) do |f| %>
    <%= f.input :artist_name, label: false, 
        input_html:{:class => 'form-control', placeholder: "Name of artist"} %>
  	<br>
    <%= f.input :artist_age, label: false, 
        input_html:{:class => 'form-control', placeholder: "Age of artist"} %>
    <br>
    <%= collection_select(:label, :label_id, Label.all, :id, 
        :label_name, :selected => @artist.label_id, :prompt => 'Please select label') %>
    <br><br>
   	<%= f.submit "Submit".html_safe, :class => 'btn btn-lg btn-success' %>
<% end %>

<br><br>
<%= link_to 'View all artists', artists_path, :class => 'btn btn-primary' %>
</div>

williams_simon/musicapp/app/views/artists/edit.html.erb
<div class="col-xs-12" >
<div class="col-xs-6 col-xs-offset-4">
<div class="well">
<h1>Edit artist: <%= @artist.artist_name %></h1>

<%= render 'form' %>

</div>
</div>
</div>

williams_simon/musicapp/app/views/artists/index.html.erb
<div class="col-xs-12" >
<div class="col-xs-10 col-xs-offset-2">
<div class="well">
<h1>Artists</h1>
<%= render 'artist_details' %>
</div>
</div>
</div>

williams_simon/musicapp/app/views/artists/new.html.erb
<div class="col-xs-12" >
<div class="col-xs-6 col-xs-offset-4">
<div class="well">
<h1>Create A New Artist</h1>

<%= render 'form' %>

</div>
</div>
</div>

williams_simon/musicapp/app/views/artists/show.html.erb
<div class="col-xs-12" >
<div class="col-xs-8 col-xs-offset-2">
<div class="well">
<h1>Artist: <%= @artist.artist_name%></h1>
<table class="table table-responsive table-bordered table-hover">
  <tr>
    <th>Artist Name</th>
    <th>Age</th>
    <th>Label</th>
  </tr>
  <tr>
		<td><%= @artist.artist_name %> </td>
		<td><%= @artist.artist_age %></td>
		<td><%= @artist.label.label_name %> </td>
		<td><%= link_to "View artist songs", artist_songs_path(@artist), 
				:class => 'btn btn-primary' %></td>
		<td><%= link_to "Edit artist", edit_artist_path(@artist),
				:class => 'btn btn-info' %></td>
		<td><%= link_to "Delete artist", artist_path(@artist),
				method: :delete, data: { confirm: 'Are you sure?' },
				:class => 'btn btn-danger' %></td>
		<br>
	</tr>
</table>
<br><br>
<%= link_to "Create a new artist", new_artist_path, :class => 'btn btn-primary' %>
<%= link_to "View all songs", songs_all_path, :class => 'btn btn-primary' %>
<%= link_to "View all labels", labels_path, :class => 'btn btn-primary' %>
<%= link_to "View all artists", artists_path, :class => 'btn btn-primary' %>
</div>
</div>
</div>

williams_simon/musicapp/app/views/labels/_form.html.erb
<div class="well">
<%= simple_form_for(@label, html: {:class => 'form-horizontal'}) do |f| %>
    <%= f.input :label_name, label: false, 
        input_html:{:class => 'form-control', placeholder: "Name of label"} %>
  	<br>
   	<%= f.submit "Submit".html_safe, :class => 'btn btn-lg btn-success' %>
<% end %>

<br><br>
<%= link_to 'View all labels', labels_path %>
</div>

williams_simon/musicapp/app/views/labels/edit.html.erb
<div class="col-xs-12" >
<div class="col-xs-6 col-xs-offset-4">
<div class="well">
<h1>Edit Label: <%= @label.label_name %></h1>

<%= render 'form' %>

</div>
</div>
</div>

williams_simon/musicapp/app/views/labels/index.html.erb
<div class="col-xs-12" >
<div class="col-xs-8 col-xs-offset-2">
<div class="well">
<h1>Labels</h1>
<table class="table table-responsive table-bordered table-hover">
  <tr>
    <th>Labels</th>
 		</tr>
		<% @labels.each do |label| %>
		<tr>
      		<td class="col-xs-4"><%= label.label_name %></td>
			<td class="col-xs-2"><%= link_to "View all artists for this label", 
				label_path(label),
				method: :post, :class => 'btn btn-primary' %></td>
			<td class="col-xs-2"><%= link_to "Edit label", edit_label_path(label), 
				:class => 'btn btn-info' %></td>
			<br>
		</tr>
	<% end %>
</table>
<br><br>
<%= link_to "Create a new label", new_label_path, :class => 'btn btn-primary' %>
<br><br>
<%= link_to "Return to list of artists", artists_path, :class => 'btn btn-primary' %>
</div>
</div>
</div>
</div>

williams_simon/musicapp/app/views/labels/new.html.erb
<div class="col-xs-12" >
<div class="col-xs-6 col-xs-offset-4">
<div class="well">
<h1>Create A New Label</h1>

<%= render 'form' %>

</div>
</div>
</div>

williams_simon/musicapp/app/views/labels/show.html.erb
<h1>All Artists For Label: <%= @label.label_name%></h1>
<table>
  <tr>
    <th>Artist Name</th>
    <th>Age</th>
  </tr>
	<% @label.artists.each do |artist| %>
		<tr>
      		<td><%= artist.artist_name %></td>
			<td><%= artist.artist_age %></td>
			<td><%= link_to "View artist songs", artist_songs_path(artist) %></td>
			<td><%= link_to "Edit artist", edit_artist_path(artist) %></td>
			<td><%= link_to "Delete artist", artist_path(artist),
					method: :delete, data: { confirm: 'Are you sure?' } %></td>
			<br>
		</tr>
	<% end %>
</table>
<br><br>
<%= link_to "Create a new artist", new_artist_path %>
<br><br>
<%= link_to "View all songs", songs_all_path %>
<br><br>
<%= link_to "View all labels", labels_path %>
<br><br>
<%= link_to "View all artists", artists_path %>
<br><br>

williams_simon/musicapp/app/views/layouts/_navigation_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
            <%=link_to "Music App", artists_path %>
      </div>
    </div>
 
      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to "Labels", labels_path %></li>
        <li><%=link_to "Artists", artists_path %></li>
        <li><%=link_to "Songs", songs_all_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account Details<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%=link_to "Your Profile", root_path %></li>
            <li><a href="#">Something Else</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Signout</a></li>
          </ul>
        </li>
      </ul>
 
  </div><!-- /.container-fluid -->
</nav>

williams_simon/musicapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Musicapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render '/layouts/navigation_header' %>

<%= yield %>

</body>
</html>

williams_simon/musicapp/app/views/songs/_create_song.html.erb
<div class="well">
<%= simple_form_for([@artist, @artist.songs.build], 
    html: {:class => 'form-horizontal'}) do |f| %>
    <%= f.input :song_name, label: false, 
        input_html:{:class => 'form-control', placeholder: "Song name"} %>
    <br>
    <%= f.input :genre, label: false, 
        input_html:{:class => 'form-control', placeholder: "Genre"} %>
    <br>
    <%= f.input :duration, label: false, 
        input_html:{:class => 'form-control', placeholder: "Song duration in seconds"} %>
    <br>
    <%= f.input :release_date, label: false,  
        input_html:{ placeholder: "Release Date"} %>
    <br>
    <%= f.submit "Submit".html_safe, :class => 'btn btn-lg btn-success' %>
<% end %>

<br><br>
<%= link_to 'View all labels', labels_path, :class => 'btn btn-lg btn-primary' %>
</div>

williams_simon/musicapp/app/views/songs/_edit_song.html.erb
<%= simple_form_for([@artist, @song], 
    html: {:class => 'form-horizontal'}) do |f| %>
    <%= f.input :song_name, label: false, 
        input_html:{:class => 'form-control', placeholder: "Song name"} %>
    <br>
    <%= f.input :genre, label: false, 
        input_html:{:class => 'form-control', placeholder: "Genre"} %>
    <br>
    <%= f.input :duration, label: false, 
        input_html:{:class => 'form-control', placeholder: "Song duration in seconds"} %>
    <br>
    <%= f.input :release_date, label: false,  
        input_html:{placeholder: "Release Date"} %>
    <br>
    <%= f.submit "Submit".html_safe, :class => 'btn btn-lg btn-success' %>
<% end %>
</br>
<%= link_to 'View all songs', songs_all_path, :class => 'btn btn-lg btn-primary' %>

williams_simon/musicapp/app/views/songs/_form.html.erb
<table class="table table-responsive table-bordered table-hover">
  <tr>
    <th>Song Title</th>
    <th>Artist Name</th>
    <th>Genre</th>
    <th>Release Date</th>
    <th>Duration</th>
  </tr>
	<% @songs.each do |song| %>
		<tr>
      	<td> <%=link_to "#{song.song_name}", artist_song_path(song.artist, song) %> </td>
     	<td> <%=link_to "#{song.artist.artist_name}", artist_path(song.artist) %> </td>
		<td><%= song.genre %></td>
		<td><%= song.release_date %></td>
		<td><%= song.duration %></td>
      	<td><%= link_to "Edit song", edit_artist_song_path(song.artist, song),
            :class => 'btn btn-info' %></td>
      	<td><%= link_to "Delete song", songs_destroy_path(song),
            method: :delete, data: { confirm: 'Are you sure?' }, 
            :class => 'btn btn-danger' %></td>
		<br>
		</tr>
	<% end %>
</table>
<br><br>
<%= link_to "Return to list of artists", artists_path,:class => 'btn btn-primary' %>

williams_simon/musicapp/app/views/songs/_song.html.erb
<div class="well">
<%= simple_form_for([@artist, @artist.songs.build], 
    html: {:class => 'form-horizontal'}) do |f| %>
    <%= f.input :song_name, label: false, 
        input_html:{:class => 'form-control', placeholder: "Song name"} %>
    <br>
    <%= f.input :genre, label: false, 
        input_html:{:class => 'form-control', placeholder: "Genre"} %>
    <br>
    <%= f.input :duration, label: false, 
        input_html:{:class => 'form-control', placeholder: "Song duration in seconds"} %>
    <br>
    <%= f.input :release_date, label: false, 
        input_html:{:class => 'form-control', placeholder: "Release Date"} %>
    <br>
    <%= f.submit "Submit".html_safe, :class => 'btn btn-lg btn-success' %>
<% end %>

<br><br>
<%= link_to 'View all labels', labels_path, :class => 'btn btn-lg btn-primary' %>
</div>

williams_simon/musicapp/app/views/songs/all.html.erb
<div class="col-xs-12" >
<div class="col-xs-10 col-xs-offset-2">
<div class="well">
<h1>View All Songs</h1>
<%= render 'form' %>
</div>
</div>
</div>

williams_simon/musicapp/app/views/songs/edit.html.erb
<div class="col-xs-12" >
<div class="col-xs-6 col-xs-offset-4">
<h1>Edit Song</h1>
<div class="well">

<%= render 'edit_song' %>

</div>

</div>
</div>

williams_simon/musicapp/app/views/songs/index.html.erb
<div class="col-xs-12" >
<div class="col-xs-10 col-xs-offset-2">
<div class="well">
<h1>Songs for: <%=@artist.artist_name %></h1>
<table class="table table-responsive table-bordered table-hover">
  <tr>
    <th>Song Title</th>
    <th>Genre</th>
    <th>Release Date</th>
    <th>Duration (secs)</th>
  </tr>
	<% @artist.songs.each do |song| %>
		<tr>
      <td><%= song.song_name %></td>
			<td><%= song.genre %></td>
			<td><%= song.release_date %></td>
			<td><%= song.duration %></td>
			<td><%= link_to "Edit song", edit_artist_song_path(song.artist, song),
            :class => 'btn btn-info' %></td>
      <td><%= link_to "Listen to song", artist_listen_song_path(song.artist, song),
            method: :post, :class => 'btn btn-info' %></td>
      <td><%= link_to "Delete song", songs_destroy_path(song),
            method: :delete, data: { confirm: 'Are you sure?' }, 
            :class => 'btn btn-danger' %></td>
			<br>
		</tr>
	<% end %>
</table>
<br><br>
<%= link_to "Create a new song", new_artist_song_path, :class => 'btn btn-primary' %>
<%= link_to "Return to list of artists", artists_path, :class => 'btn btn-primary' %>
</div>
</div>
</div>

williams_simon/musicapp/app/views/songs/listen.html.erb
<div class="col-xs-12" >
<div class="col-xs-10 col-xs-offset-2">
<div class="well">
<h1>Listen to: <%=@song.song_name %></h1>
<table class="table table-responsive table-bordered table-hover">
  <tr>
    <th>Song Title</th>
    <th>Artist Name</th>
    <th>Genre</th>
    <th>Release Date</th>
    <th>Duration</th>
    <th>Listen</th>
  </tr>
  <tr>
    <td> <%= @song.song_name %> </td>
    <td> <%= @song.artist.artist_name %> </td>
	<td><%= @song.genre %></td>
	<td><%= @song.release_date %></td>
	<td><%= @song.duration %></td>
  <% if @artist_song_detail == {} %>
        <td> No media available</td>
    <% else %>
        <td><%= link_to "Listen", "#{@artist_song_detail[@song.artist.artist_name]}" %></td>
    <% end %>
  </br>
  </tr>
</table>

</div>
</div>
</div>

williams_simon/musicapp/app/views/songs/new.html.erb
<div class="col-xs-12" >
<div class="col-xs-6 col-xs-offset-4">
<h1>Create A New Song For: <%=@artist.artist_name %></h1>

<%= render 'create_song' %>

</div>
</div>